### PR TITLE
Migrate to "hcxpcapngtool"

### PR DESCRIPTION
**Pull request by cikeZ00**
Since "hcxpcaptool" is now deprecated, "hcxpcapngtool" was made to replace it.

This is just a simple command fix.

### CODE REVIEW

**Comment by cikeZ00** [comment]
Do note. This outputs the new 22000 format instead of 16800.

**Comment by CyrisXD** [comment]
Thanks for this, would you mind updating any documentation to accomodate the new tool? I don't have any of the tools anymore to test and validate.

**Comment by cikeZ00** [comment]
It works the same as the old tool (same link too).
Main difference is the name and parameters.
The end user follows the same process as before.

If needed I could also just add a notice that the 16800 format is deprecated.

**Comment by CyrisXD** [comment]
Perfect, thanks for your contribution.

**Pull request merged**
